// Generated by CoffeeScript 1.7.1
(function() {
  var module;

  module = angular.module('atns.ng.buildversion', ['build-version', 'atns.ng.messages']);

  module.config(function($httpProvider) {
    return $httpProvider.interceptors.push(function($q, $rootScope) {
      return {
        response: function(response) {
          var version;
          version = response.headers('X-Application-Version');
          if (version) {
            $rootScope.ServerVersion = version;
          }
          return response || $q.when(response);
        }
      };
    });
  });

  module.run(function($rootScope, BuildVersion) {
    var reload;
    $rootScope.BuildVersion = BuildVersion;
    reload = function() {
      return window.location.reload(true);
    };
    $rootScope.showVersionDialog = function() {
      return $rootScope.confirmDialog('Veraltete Webversion', 'Ihr Webversion ist veraltet und muss aktualisiert werden. Drücken Sie dazu auf "Neu Laden".', 'Neu Laden', reload);
    };
    return $rootScope.$watch('ServerVersion', function(serverVersion) {
      if (!serverVersion) {
        return;
      }
      if (BuildVersion.indexOf('dirty') > -1) {
        return;
      }
      if (serverVersion !== BuildVersion && $rootScope.showVersionWarning !== serverVersion) {
        $rootScope.showVersionWarning = serverVersion;
        return $rootScope.showVersionDialog();
      }
    });
  });

}).call(this);
